name: RapineMarket
version: '1.0'
main: rapine.rapinemarket.RapineMarket
api-version: '1.17'
depend: [LuckPerms]
softdepend: [PlaceholderAPI, SkinsRestorer]
description: Plugin for market robberies with hostages and police interactions

commands:
  marketselector:
    description: Get the market region selector tool
    usage: /marketselector get
    permission: rapinemarket.admin
  market:
    description: Create a market region
    usage: /market create <n> | /market delete <n> | /market list | /market rename <old_name> <new_name>
    permission: rapinemarket.admin
  cassaforte:
    description: Get a safe block
    usage: /cassaforte get
    permission: rapinemarket.admin
  soldisporchi:
    description: Get dirty money
    usage: /soldisporchi get <amount>
    permission: rapinemarket.admin
  ostaggio:
    description: Set a player as hostage during robbery
    usage: /ostaggio <player>
  rapinatime:
    description: Check the remaining time of the robbery
    usage: /rapinatime
    aliases: [rt, tempo]
  rapinaologramma:
    description: Gestisce gli ologrammi delle rapine
    usage: /rapinaologramma set|remove|move|list <nome_market>
    permission: rapina.ologramma
  rapinehelp:
    description: Mostra l'aiuto per tutti i comandi del plugin
    usage: /rapinehelp [admin|player|rapina]
    aliases: [rhelp]

permissions:
  rapinemarket.admin:
    description: Allows access to admin commands
    default: op
  rapina.ologramma:
    description: Allows access to hologram commands
    default: op
